---

# Create a crontab to regularly update the users/groups json file with latest user and group information.
# This is used to create matching local users on all compute node instances and
# Should only be installed on 1 instance.
- name: Create /etc/cron.d/slurm_users_groups_json
  template:
    dest: /etc/cron.d/soca_{{ClusterName}}_create_users_groups_json
    src:   etc/cron.d/soca_users_groups_json
    owner: root
    group: root
    mode: 0600
    force: yes

- name: Create {{ScriptsDir}}/create_users_groups_json.py
  template:
    dest: "{{ScriptsDir}}/create_users_groups_json.py"
    src: opt/slurm/cluster/bin/create_users_groups_json.py
    owner: root
    group: root
    mode: 0700

- name: Create {{ScriptsDir}}/create_users_groups.py
  template:
    src:   scripts/create_users_groups.py
    dest: "{{ScriptsDir}}/create_users_groups.py"
    owner: root
    group: root
    mode: 0700
