
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LSFClusterName:
    Description: "The name of the LSF cluster."
    Type: "String"
    Default: "cde-1"

Resources:
  DCVCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/DCVCredentialsSecret'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "simuser"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  FSxCredentialsSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: !Sub '${AWS::StackName}/FSxCredentialsSecret'
        GenerateSecretString:
          SecretStringTemplate: '{"username": "fsxadmin"}'
          GenerateStringKey: "password"
          PasswordLength: 16
          RequireEachIncludedType: True

Outputs:
  DCVCredentialsSecretArn:
    Description: DCV password in Secrets Manager
    Value: !Ref DCVCredentialsSecret
    Export:
      Name: !Join [ '-', [ !Ref LSFClusterName, "DCVSecretARN" ] ]

  FSxCredentialsSecretArn:
    Description: FSxN admin password in Secrets Manager
    Value: !Ref FSxCredentialsSecret
    Export:
      Name: !Join [ '-', [ !Ref LSFClusterName, "FSxNAdminSecretARN" ] ]
